[project]
name = "backend"
version = "0.1.0"
description = "Backend portion for SWE40006 Project"
readme = "README.md"
authors = [
    { name = "Tom Goodison", email = "tom@tomgoodo.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.141.1",
    "sqlalchemy>=2.0.54",
    "uvicorn>=0.53.0",
]

[project.scripts]
backend = "backend:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.8",
]
